#!/usr/bin/env python3

## FIXME: Support multi-valued attributes

import sys
import csv
import json

csv_reader = csv.reader(sys.stdin)

try:
    csv_h = next(csv_reader)
except StopIteration:
    sys.exit(0)

for csv_r in csv_reader:
    r = dict(zip(csv_h, csv_r))
    json_str = json.dumps(r, ensure_ascii=False, sort_keys=False, indent=2)
    print(json_str)

sys.exit(0)
