#!/usr/bin/env python3

## FIXME: Support multi-valued attributes

import sys
import csv
import yaml

csv_reader = csv.reader(sys.stdin)

try:
    csv_h = next(csv_reader)
except StopIteration:
    sys.exit(0)

for csv_r in csv_reader:
    r = dict(zip(csv_h, csv_r))
    yaml_str = yaml.dump(r, allow_unicode=True, sort_keys=False, indent=2)
    print(yaml_str)

sys.exit(0)
