#!/bin/bash
#
# DNS: Query and inspect a DMARC policy
#
# SPDX-FileCopyrightText: 2026 SATOH Fumiyasu @ OSSTech Corp., Japan
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -u
set -o pipefail || exit $?
shopt -s lastpipe || exit $?

set -f  # noglob

perr() {
  echo "$0: ERROR: $1" 1>&2
}

pdie() {
  perr "$1"
  exit "${2-1}"
}

if [[ -t 1 ]]; then
    c_reset=$'\x1b[m'
    c_red=$'\x1b[31m'
    c_green=$'\x1b[32m'
    c_yellow=$'\x1b[33m'
    c_blue=$'\x1b[34m'
    c_magenta=$'\x1b[35m'
    c_cyan=$'\x1b[36m'
else
    c_reset=
    c_red=
    c_green=
    c_yellow=
    c_blue=
    c_magenta=
    c_cyan=
fi

p_section() {
    echo "${c_green}$*${c_reset}:"
}
p_item() {
  echo "  ${c_cyan}$1${c_reset}${2+	$2}${3+ ${c_blue}($3)${c_reset}}"
}

tags=(
'v	required	-	Version'
'p	required	-	Policy'
'sp	optional	->p	Subdomain Policy'
'pct	optional	100	Percentage'
'adkim	optional	r	Alignment mode for DKIM'
'aspf	optional	r	Alignment mode for SPF'
'rua	optional	-	Reporting URI for Aggregate data'
'ruf	optional	-	Reporting URI for Forensic data'
'fo	optional	0	Failure Reporting Options'
'rf	optional	afrf	Reporting Format'
'ri	optional	86400	Reporting Interval'
)

typeset -A tag_required=() tag_default=() tag_description=()
for tag in "${tags[@]}"; do
    IFS=$'\t' read -r name required default description <<<"$tag"
    if [[ $required == "required" ]]; then
        tag_required[$name]="set"
    fi
    tag_default[$name]="$default"
    tag_description[$name]="$description"
done

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 DOMAIN [NAMESERVER]"
    exit 64  ## EX_USAGE
fi

domain_name="$1"; shift
if [[ $domain_name == "-" ]]; then
    lookup_cmd=(cat)
else
    dmarc_name="_dmarc.${domain_name%.}"
    lookup_cmd=(dig +noall +answer -t txt ${1+"@$1"} "$dmarc_name")
fi

rr=$("${lookup_cmd[@]}")
if [[ -z "$rr" ]]; then
    pdie "No DMARC policy found"
fi

typeset -A tag_value=()
IFS=$' \t' read -r rr_name rr_ttl rr_class rr_type rr_data <<<"$rr"
IFS=' ;'
for v in ${rr_data//\"/}; do
    tag_value["${v%%=*}"]="${v#*=}"
done

if [[ "$lookup_cmd" != "cat" ]]; then
    p_section 'Command'
    p_item "${lookup_cmd[*]}"
fi
p_section 'DMARC DNS RR'
p_item "Name" "$rr_name"
p_item "TTL" "$rr_ttl"
p_item "Class" "$rr_class"
p_item "Type" "$rr_type"
p_item "Data" "$rr_data"
p_section 'Explicit DMARC Policy'
for tag_name in "${!tag_required[@]}"; do
    if [[ -z ${tag_value[$tag_name]+set} ]]; then
        pdie "No required tag in the DMARC policy: $tag_name"
    fi
    p_item "$tag_name" "${tag_value[$tag_name]}" "${tag_description[$tag_name]}"
done
for tag_name in "${!tag_value[@]}"; do
    if [[ -n "${tag_required[$tag_name]+set}" ]]; then
        continue
    fi
    p_item "$tag_name" "${tag_value[$tag_name]}" "${tag_description[$tag_name]}"
done

p_section 'Implicit DMARC Policy'
for tag_name in "${!tag_default[@]}"; do
    if [[ -n ${tag_value[$tag_name]+set} ]]; then
        continue
    fi
    default="${tag_default[$tag_name]}"
    if [[ "$default" == "->"* ]]; then
        default="${tag_value[${default#->}]-?}"
    fi
    p_item "$tag_name" "$default" "${tag_description[$tag_name]}"
done
