#!/bin/bash
## -*- encoding: utf-8 -*- vim:tabstop=8:shiftwidth=2
##
## ＿人人人人人人＿
## ＞　突然の死　＜ ジェネレーター (Echo "sudden death" message)
## ￣Y^Y^Y^Y^Y^Y￣
## Copyright (C) 2013 SATOH Fumiyasu @ OSS Technology Corp., Japan
##               <https://github.com/fumiyas/home-commands/blob/master/echo-sd>
##               <http://www.OSSTech.co.jp/cgi-bin/echo-sd>
##               <https://twitter.com/satoh_fumiyasu>
##
## License: GNU General Public License version 3
##
## Requirements: bash 4.0, ksh 93u or zsh 4.3
##
## How to install:
##
##   $ mkdir -p $HOME/bin
##   $ cd $HOME/bin
##   $ wget -q https://raw.github.com/fumiyas/home-commands/master/echo-sd
##   $ chmod +x echo-sd
##   $ export PATH="$HOME/bin:$PATH"
##   $ alias echo=echo-sd
##   $ alias banner=echo-sd
##
## Examples for Command-line mode:
##
##   $ echo-sd
##    ＿人人人人人人＿
##   ＞　突然の死　＜
##   ￣Y^Y^Y^Y^Y^Y￣
##   $ echo-sd ぬるぽっ！!
##   ＿人人人人人人人人＿
##   ＞　ぬるぽっ！！　＜
##   ￣Y^Y^Y^Y^Y^YY^^Y￣
##   $ echo-sd -v ガッ！
##   ＿人人＿
##   ＞ ガ ＜
##   ＞ ッ ＜
##   ＞ ！ ＜
##   ￣Y^Y￣
##   $ echo-sd -m 1 ズキュウウゥン！！
##   ＿人人人人人人人人人人人人＿
##   ＞　　　　　　　　　　　　＜
##   ＞　 ズキュウウゥン！！ 　＜
##   ＞　　　　　　　　　　　　＜
##   ￣Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y￣
##   $ echo-sd -v -t 1 -b 1 -l 6 -r 8 ｺﾞｺﾞｺﾞｺﾞｺﾞｺﾞｺﾞｺﾞ 「世界」ッ！ 時よ止まれ！
##   ＿人人人人人人人人人人人人人＿
##   ＞　　　　　　　　　　　　　＜
##   ＞　　　 時　 ┐ ｺﾞ　　　　 ＜
##   ＞　　　 よ　世　ｺﾞ　　　　 ＜
##   ＞　　　 止　界　ｺﾞ　　　　 ＜
##   ＞　　　 ま └　 ｺﾞ　　　　 ＜
##   ＞　　　 れ　ッ　ｺﾞ　　　　 ＜
##   ＞　　　 ！　！　ｺﾞ　　　　 ＜
##   ＞　　　　　　　 ｺﾞ　　　　 ＜
##   ＞　　　　　　　 ｺﾞ　　　　 ＜
##   ＞　　　　　　　　　　　　　＜
##   ￣Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y￣
##
## Examples for CGI mode:
##
##   $ GATEWAY_INTERFACE=CGI/1.0 QUERY_STRING=s=おっす！\&o=v echo-sd
##   Content-Type: text/html; charset=UTF-8
##   ...
##   <pre>
##   ＿人人＿
##   ＞ お ＜
##   ＞ っ ＜
##   ＞ す ＜
##   ＞ ！ ＜
##   ￣Y^Y￣
##   </pre><hr>
##   ...
##
## On-line demo site:
##
##   http://www.OSSTech.co.jp/cgi-bin/echo-sd
##
## TODO:
##
##   * Nothing
##
## Inspired by:
##
##   * 突然の死ジェネレータ - powered by starwing.net, created by @karno.
##     http://starwing.net/suddenly_death.html
##   * 突然の死ジェネレータ - 純粋関数空間
##     http://tanakh.jp/tools/sudden.html
##   * 元ネタ
##     http://dic.nicovideo.jp/a/%E7%AA%81%E7%84%B6%E3%81%AE%E6%AD%BB
##

if [[ ${0##*/} == echo-sd ]] && [[ ${zsh_eval_context-toplevel} == toplevel ]]; then
  set -u
fi

typeset SD_arg0="$0"
typeset SD_copyright='(C) 2013 SATOH Fumiyasu @ OSS Technology Corp., Japan'
typeset SD_url='https://github.com/fumiyas/home-commands/blob/master/echo-sd'
typeset SD_lang_orig SD_lang
typeset SD_c_tl SD_c_t SD_c_tr
typeset SD_c_l SD_c_r
typeset SD_c_bl SD_c_b SD_c_br
typeset -A SD_v_map

function SD_die {
  SD_echo_command "${SD_arg0##*/}: ERROR: $1" 1>&2
  SD_echo_command 1>&2
  exit ${2-1}
}

function SD_init {
  if [[ -n ${ZSH_VERSION-} ]]; then
    setopt SH_WORD_SPLIT
    setopt KSH_GLOB
    setopt KSH_ARRAYS
  fi

  typeset lang_ja lang

  SD_lang_orig="${LANG-}"
  if [[ ${SD_lang_orig#*.} != @(UTF-8|utf-8|UTF8|utf8) ]]; then
    if type SD_locale >/dev/null 2>&1; then
      while read -r SD_locale; do
	if [[ ${SD_locale#*.} == @(UTF-8|utf-8|UTF8|utf8) ]]; then
	  if [[ ${SD_locale%.*} == ja_JP ]]; then
	    lang_ja="$SD_locale"
	  else
	    lang="$SD_locale"
	  fi
	fi
      done < <(locale -a)
    fi
  fi
  SD_lang="${lang_ja-${lang-ja_JP.UTF-8}}"

  SD_c_tl="＿人"
  SD_c_t="人"
  SD_c_tr="人＿"
  SD_c_l="＞"
  SD_c_r="＜"
  SD_c_bl="￣Y^"
  SD_c_b="Y^"
  SD_c_br="Y￣"

  if [[ -n ${ZSH_VERSION-} ]]; then
    SD_v_map=()
  else
    SD_v_map=
  fi
  SD_v_map[。]='  。'
  SD_v_map[、]='  、'
  SD_v_map[ー]=' ｜ '
  SD_v_map[…]=' ︙ '
  SD_v_map[‥]=' ︰ '
  SD_v_map[（]=' ⏜  '
  SD_v_map[\(]=' ⏜  '
  SD_v_map[）]=' ⏝  '
  SD_v_map[\)]=' ⏝  '
  SD_v_map[［]=' ⎴  '
  SD_v_map[\[]=' ⎴  '
  SD_v_map[］]=' ⎵  '
  SD_v_map[\]]=' ⎵  '
  SD_v_map[｛]=' ⏞  '
  SD_v_map[\{]=' ⏞  '
  SD_v_map[｝]=' ⏟  '
  SD_v_map[\}]=' ⏟  '
  SD_v_map[「]='  ┐'
  SD_v_map[」]='└  '
  SD_v_map[｢]='  ┐'
  SD_v_map[｣]='└  '
  SD_v_map[-]=' |  '
  SD_v_map[ｰ]=' |  '
  SD_v_map[,]="  ' "
  SD_v_map[､]='  ` '
}

function _SD_fill_string_by_char {
  typeset str char
  str="$1"; shift
  char="$1"; shift

  ## Why bash on ja_JP.UTF-8 locale matches '[¥]' with '︙' (and others?)
  #str="${str//[ -~｡-ﾟ¢£¥¦¬¯]/$char}"
  str="${str//[ -~｡-ﾟ¢£¦¬¯]/$char}"
  str="${str//¥/$char}"
  str="${str//[! ]/$char$char}"

  echo "$str"
}

function _SD_pad_space {
  printf "%${1}s" ''
}

function _SD_string_width {
  typeset str
  str=$(_SD_fill_string_by_char "$1" ' ')

  echo "${#str}"
}

function _SD_echo_with_padding {
  typeset str width
  str="$1"; shift
  width="$1"; shift

  echo "${str}$(_SD_pad_space "$((width-$(_SD_string_width "${1-$str}")))")"
}

function SD_echo_horizontal {
  typeset opt
  typeset margin_top=0 margin_bottom=0 margin_left=0 margin_right=0

  while [ "$#" -gt 0 ]; do
    opt="$1"; shift

    if [[ -z "${opt##-[!-]?*}" ]]; then
      set -- "-${opt#??}" ${1+"$@"}
      opt="${opt%${1#-}}"
    fi
    if [[ -z "${opt##--*=*}" ]]; then
      set -- "${opt#--*=}" ${1+"$@"}
      opt="${opt%%=*}"
    fi

    case "$opt" in
    -m|--margin)
      if [[ ${1-BAD} == @(*[!0-9]*) ]]; then
	SD_die "Invalid option value: $opt ${1-UNSPECIFIED}"
      fi
      margin_top="$((($1 + 1) / 2))"
      margin_bottom="$margin_top"
      margin_left="$1"
      margin_right="$1"
      shift
      ;;
    -[tblr]|--margin-top|--margin-bottom|--margin-left|--margin-right)
      if [[ ${1-BAD} == @(*[!0-9]*) ]]; then
	SD_die "Invalid option value: $opt ${1-UNSPECIFIED}"
      fi
      case "$opt" in
      -t|--margin-top)
	margin_top="$1"
	;;
      -b|--margin-bottom)
	margin_bottom="$1"
	;;
      -l|--margin-left)
	margin_left="$1"
	;;
      -r|--margin-right)
	margin_right="$1"
	;;
      esac
      shift
      ;;
    --)
      break
      ;;
    -*)
      SD_die "Invalid option: $opt"
      ;;
    *)
      set -- "$opt" ${1+"$@"}
      break
      ;;
    esac
  done

  export LANG="$SD_lang"

  typeset -a scripts
  typeset script width width_tmp
  typeset margin_left_s margin_right_s
  width=0
  margin_left_s=$(_SD_pad_space "$margin_left")
  margin_right_s=$(_SD_pad_space "$margin_right")
  for script in ${1+"$@"}; do
    script="$margin_left_s$script$margin_right_s"
    scripts[${#scripts[@]}]="$script"
    width_tmp=$(_SD_string_width "$script")
    if [[ $width_tmp -gt $width ]]; then
      width="$width_tmp"
    fi
  done

  typeset template header footer
  template=$(_SD_pad_space "$width")
  header="${SD_c_tl}${template//  /${SD_c_t}}${SD_c_tr}"
  footer="${SD_c_bl}${template//  /${SD_c_b}}${SD_c_br}"

  while [[ $margin_top -gt 0 ]]; do
    scripts=('' ${scripts[@]+"${scripts[@]}"})
    let margin_top--
  done
  while [[ $margin_bottom -gt 0 ]]; do
    scripts[${#scripts[@]}]=''
    let margin_bottom--
  done

  echo "${header/ /}"
  typeset line
  for script in ${scripts[@]+"${scripts[@]}"}; do
    line="${SD_c_l}　$(_SD_echo_with_padding "${script}" "$width")　${SD_c_r}"
    echo "${line//  /　}"
  done
  echo "${footer/ /}"

  export LANG="$SD_lang_orig"
}

function SD_echo_vertical {
  typeset opt
  typeset margin_top=0 margin_bottom=0 margin_left=0 margin_right=0

  while [ "$#" -gt 0 ]; do
    opt="$1"; shift

    if [[ -z "${opt##-[!-]?*}" ]]; then
      set -- "-${opt#??}" ${1+"$@"}
      opt="${opt%${1#-}}"
    fi
    if [[ -z "${opt##--*=*}" ]]; then
      set -- "${opt#--*=}" ${1+"$@"}
      opt="${opt%%=*}"
    fi

    case "$opt" in
    -m|--margin)
      if [[ ${1-BAD} == @(*[!0-9]*) ]]; then
	SD_die "Invalid option value: $opt ${1-UNSPECIFIED}"
      fi
      margin_top="$((($1 + 1) / 2))"
      margin_bottom="$margin_top"
      margin_left="$1"
      margin_right="$1"
      shift
      ;;
    -[tblr]|--margin-top|--margin-bottom|--margin-left|--margin-right)
      if [[ ${1-BAD} == @(*[!0-9]*) ]]; then
	SD_die "Invalid option value: $opt ${1-UNSPECIFIED}"
      fi
      case "$opt" in
      -t|--margin-top)
	margin_top="$1"
	;;
      -b|--margin-bottom)
	margin_bottom="$1"
	;;
      -l|--margin-left)
	margin_left="$1"
	;;
      -r|--margin-right)
	margin_right="$1"
	;;
      esac
      shift
      ;;
    --)
      break
      ;;
    -*)
      SD_die "Invalid option: $opt"
      ;;
    *)
      set -- "$opt" ${1+"$@"}
      break
      ;;
    esac
  done

  export LANG="$SD_lang"

  typeset -a lines
  typeset line line_n pad_n
  typeset script script_n trailer trailer2 letter letter_width next
  typeset margin_top_s margin_bottom_s
  letter_width=4
  script_n=0
  margin_top_s=$(_SD_pad_space "$margin_top")
  margin_bottom_s=$(_SD_pad_space "$margin_bottom")
  for script in ${1+"$@"}; do
    line_n=0
    script="$margin_top_s$script$margin_bottom_s"
    trailer="$script"

    while [[ -n $script ]]; do
      trailer="${trailer#?}"
      letter="${script%$trailer}"
      script="${script#?}"
      if [[ -n ${SD_v_map[$letter]-} ]]; then
	line="${SD_v_map[$letter]}"
      else
	trailer2="${trailer#?}"
	next="${script%$trailer2}"
	if [[ $next == @(ﾞ|ﾟ) ]] || [[ $letter$next == @([\?!][\?!]) ]]; then
	  line=" $letter$next "
	  trailer="$trailer2"
	  script="${script#?}"
	else
	  line=" ${letter} "
	fi
      fi

      if [[ -z ${lines[$line_n]-} ]]; then
	lines[$line_n]="$(_SD_pad_space $((script_n * $letter_width)))"
      fi
      lines[$line_n]="$(_SD_echo_with_padding "${line}" $letter_width)${lines[$line_n]}"
      let line_n+=1
    done

    while [[ $line_n -lt ${#lines[@]} ]]; do
      lines[$line_n]="$(_SD_pad_space $letter_width)${lines[$line_n]}"
      let line_n+=1
    done

    let script_n+=1
  done

  typeset line_width=$(((script_n - 1) * $letter_width))
  let line_width+=$margin_left+$margin_right

  typeset template header footer
  template=$(_SD_pad_space "$line_width")
  header="${SD_c_tl}${template//  /${SD_c_t}}${SD_c_tr}"
  footer="${SD_c_bl}${template//  /${SD_c_b}}${SD_c_br}"

  typeset margin_left_s margin_right_s
  margin_left_s=$(_SD_pad_space "$margin_left")
  margin_right_s=$(_SD_pad_space "$margin_right")

  echo "${header/ /}"
  for line in ${lines[@]+"${lines[@]}"}; do
    line="$margin_left_s$line$margin_right_s"
    echo "${SD_c_l}${line//  /　}${SD_c_r}"
  done
  echo "${footer/ /}"

  export LANG="$SD_lang_orig"
}

function SD_echo_command_help {
  {
    SD_c_r="＜ ジェネレーター" SD_echo_command
    cat <<EOT
Usage: ${SD_arg0##*/} [OPTIONS] [SCRIPT ...]

Options:
 -h, --help
    Print this message
 -s, --read-stdin
    Read scripts from stdin
 -v, --vertical
    Print scripts vertically
 -m, --margin MARGIN
 -t, --margin-top MARGIN
 -b, --margin-bottom MARGIN
 -l, --margin-left MARGIN
 -r, --margin-right MARGIN
    Margin size
EOT
  } |SD_echo_command --read-stdin
}

function SD_echo_command {
  typeset opt read_stdin vertical
  typeset margin margin_top margin_bottom margin_left margin_right

  while [ "$#" -gt 0 ]; do
    opt="$1"; shift

    if [[ -z "${opt##-[!-]?*}" ]]; then
      set -- "-${opt#??}" ${1+"$@"}
      opt="${opt%${1#-}}"
    fi
    if [[ -z "${opt##--*=*}" ]]; then
      set -- "${opt#--*=}" ${1+"$@"}
      opt="${opt%%=*}"
    fi

    case "$opt" in
    -h|--help)
      SD_echo_command_help
      exit 0
      ;;
    -s|--read-stdin)
      read_stdin="set"
      ;;
    -v|--vertical)
      vertical="set"
      ;;
    -m|--margin)
      if [[ ${1-BAD} == @(*[!0-9]*) ]]; then
	SD_die "Invalid option value: $opt ${1-UNSPECIFIED}"
      fi
      margin="$1"
      shift
      ;;
    -[tblr]|--margin-top|--margin-bottom|--margin-left|--margin-right)
      if [[ ${1-BAD} == @(*[!0-9]*) ]]; then
	SD_die "Invalid option value: $opt ${1-UNSPECIFIED}"
      fi
      case "$opt" in
      -t|--margin-top)
	margin_top="$1"
	;;
      -b|--margin-bottom)
	margin_bottom="$1"
	;;
      -l|--margin-left)
	margin_left="$1"
	;;
      -r|--margin-right)
	margin_right="$1"
	;;
      esac
      shift
      ;;
    --)
      break
      ;;
    -*)
      SD_die "Invalid option: $opt"
      ;;
    *)
      set -- "$opt" ${1+"$@"}
      break
      ;;
    esac
  done

  if [[ -n ${read_stdin-} ]]; then
    while IFS= read -r line; do
      set -- ${1+"$@"} "$line"
    done
  fi

  if [[ $# -eq 0 ]]; then
    set -- '突然の死'
  fi

  if [[ -z ${vertical-} ]]; then
    SD_echo_horizontal \
      ${margin:+-m "$margin"} \
      ${margin_top:+-t "$margin_top"} \
      ${margin_bottom:+-b "$margin_bottom"} \
      ${margin_left:+-l "$margin_left"} \
      ${margin_right:+-r "$margin_right"} \
      -- \
      ${1+"$@"} \
      ;
  else
    SD_echo_vertical \
      ${margin:+-m "$margin"} \
      ${margin_top:+-t "$margin_top"} \
      ${margin_bottom:+-b "$margin_bottom"} \
      ${margin_left:+-l "$margin_left"} \
      ${margin_right:+-r "$margin_right"} \
      -- \
      ${1+"$@"} \
      ;
  fi
}

function _SD_escape_html {
  if [[ -n ${1+set} ]]; then
    echo "$1"
  else
    cat
  fi \
  |sed \
    -e 's/&/\&amp;/g;' \
    -e 's/</\&lt;/g;' \
    -e 's/>/\&gt;/g;' \
    ;
}

function _SD_urldecode {
  ## FIXME: Support ksh
  echo -e "$(echo "$1" |sed 's/+/ /g;s/%\(..\)/\\x\1/g;')"
}

function SD_echo_cgi {
  typeset query="${QUERY_STRING-}"
  typeset param value
  typeset text vmargin vertical
  typeset -a prefaces
  typeset -a scripts

  while [[ -n $query ]]; do
    param="${query%%&*}"
    name="$(_SD_urldecode "${param%%=*}")"
    value="$(_SD_urldecode "${param#*=}")"

    case "$name" in
    o|options)
      case "$value" in
      text)
	text="checked"
	;;
      1|vmargin)
	vmargin="checked"
	;;
      v|vertical)
	vertical="checked"
	;;
      esac
      ;;
    p|prefaces)
      while IFS= read -r line; do
	prefaces[${#prefaces[@]}]="${line%}"
      done < <(echo "$value")
      ;;
    s|scripts)
      while IFS= read -r line; do
	scripts[${#scripts[@]}]="${line%}"
      done < <(echo "$value")
      ;;
    esac

    if [[ -n ${query##*&*} ]]; then
      break
    fi
    query="${query#*&}"
  done

  set -- \
    ${vmargin:+-t 1} \
    ${vmargin:+-b 1} \
    ${vertical:+-v} \
    -- \
    ;
  if [[ ${#scripts[@]} -eq 1 ]] && [[ -z ${scripts[0]} ]]; then
    set -- ${1+"$@"} '突然の死'
  else
    set -- ${1+"$@"} ${scripts[@]+"${scripts[@]}"}
  fi

  if [[ -n ${text-} ]]; then
    echo 'Content-Type: text/plain; charset=UTF-8'
    echo
    for preface in ${prefaces[@]+"${prefaces[@]}"}; do
      echo "$preface"
    done
    SD_echo_command "$@"
  else
    echo 'Content-Type: text/html; charset=UTF-8'
    echo
    echo \
      '<html>' \
      '<head><title>＞　突然の死　＜ ジェネレーター</title></head>' \
      '<style type="text/css"><!--' \
      '.ul { text-decoration:underline; }' \
      '--></style>' \
      '<body><h1>＞　突然の死　＜ ジェネレーター</h1>' \
      '<form action="./echo-sd" method="GET">' \
      ;
    echo -n '<textarea name="scripts" cols="80" rows="4" tabindex="1">'
    for script in ${scripts[@]+"${scripts[@]}"}; do
      _SD_escape_html "$script"
    done
    echo '</textarea><br>'
    echo '<label>' \
      '<input type="checkbox" name="options" value="vmargin" accesskey="1" ' \
      "${vmargin-}>上下空白(<span class='ul'>1</span>)</label>"
    echo '<label>' \
      '<input type="checkbox" name="options" value="vertical" accesskey="v" ' \
      "${vertical-}>縦書き(<span class='ul'>V</span>)</label>"
    echo '<label>' \
      '<input type="checkbox" name="options" value="text" accesskey="t" ' \
      ">テキスト(<span class='ul'>T</span>)</label>"
    echo '<br>'
    echo '<input type='submit' value='＞　ジェネレート　＜' tabindex="2"><br>'
    echo '</form>'
    echo '<!--'
    echo "[$(_SD_escape_html "$*")]"
    echo '-->'
    echo '<pre>'
    for preface in ${prefaces[@]+"${prefaces[@]}"}; do
      _SD_escape_html "$preface"
    done
    SD_echo_command "$@" |_SD_escape_html
    echo '</pre><hr>'
    _SD_escape_html "$SD_copyright"
    echo '<br>'
    echo "<a href='$(_SD_escape_html "$SD_url")'>$(_SD_escape_html "$SD_url")</a>"
    echo '<br>'
    echo "${SD_CGI_FOOTER_HTML-}"
    echo '</body></html>'
  fi
}

if [[ ${0##*/} == echo-sd ]] && [[ ${zsh_eval_context-toplevel} == toplevel ]]; then
  SD_init

  if [[ ${GATEWAY_INTERFACE-} == @(CGI*) ]]; then
    SD_echo_cgi "$@"
  else
    SD_echo_command "$@"
  fi
  exit $?
fi

return 0

