#!/bin/bash

set -u

git_comment_str=$(git config get core.commentString)

{
  echo
  echo "$git_comment_str ------------------------ >8 ------------------------"
  echo "$git_comment_str Previous git log"
  git log |head -n 1000
} >> "${@: -1}"

exec "$EDITOR" "$@"
