#!/usr/bin/env python3
# -*- coding: utf-8 -*- vim:shiftwidth=4:expandtab:
#
# Sort JSONL input by a value of the specified key and write to the named files
#
# SPDX-FileCopyrightText: 20XX SATOH Fumiyasu @ OSSTech Corp., Japan
# SPDX-License-Identifier: GPL-3.0-or-later
#
# /// script
# requires-python = ">=3.6"
# dependencies = [
# ]
# ///

import sys
import json


def main(argv):
    key = argv[0]
    ext = argv[1]

    names = set()
    for line_no, line in enumerate(sys.stdin, start=1):
        try:
            entry = json.loads(line)
        except json.decoder.JSONDecodeError:
            print(f"ERROR: Invalid JSONL input: line {line_no}: {line!r}", file=sys.stderr)
            sys.exit(1)

        name = entry[key] if key in entry else "NONE"
        fname = f"{name}.{ext}"
        if name in names:
            os.remove(fname)
            names.append(name)
        with open(fname, "a") as f:
            print(json.dumps(entry), file=f)

    sys.exit(0)


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} KEY FILEEXT")
        sys.exit(1)

    sys.exit(main(sys.argv[1:]))
