#!/bin/bash
##
## jwdiff: Display word differences between Japanese text files
## Copyright (c) 2013 SATOH Fumiyasu @ OSS Technology Corp., Japan
##               <http://fumiyas.github.io/>
##
## URL: https://github.com/fumiyas/home-commands/blob/master/jwdiff
## License: GNU General Public License version 3
##

set -u

wakati() {
  expand "$1" \
    |mecab \
      --node-format '%M\t' \
      --eos-format '\n' \
  ;
}

usage="\
Usage: ${0##*/} [OPTION] FILE1 FILE2

Options: See wdiff(1) manpage except --diff-input (-d) option
"

if [[ $# -lt 2 ]]; then
  echo "$usage" 1>&2
  exit 1
fi

args=("$@")
args_last=$((${#args[@]} - 1))
file2="${args[$args_last]}";
unset args[$args_last]
let args_last--
file1="${args[$args_last]}";
unset args[$args_last]

wdiff \
  ${args+"${args[@]}"} \
  <(wakati "$file1") \
  <(wakati "$file2") \
|sed 's/	//g' \
;

