#!/bin/bash
##
## List specified files and all origin directories
##
## SPDX-FileCopyrightText: 2013-2025 SATOH Fumiyasu @ OSSTech Corp., Japan
## SPDX-License-Identifier: GPL-3.0-or-later
##

set -u

cmd="ls"
cmd_opts=()

if [[ ${1-} == --command=* ]]; then
  cmd="${1#--command=}"
  shift
fi

if [[ ${cmd##*/} == "ls" ]]; then
  cmd_opts+=(-d)
fi

while [[ $# -gt 0 ]]; do
  [[ $1 == "--" ]] && { shift; break; }
  [[ -n "${1##-*}" ]] && break
  cmd_opts+=("$1")
  shift
done

if [[ $# -eq 0 ]]; then
  echo "Usage: $0 [--command=COMMAND] [COMMAND OPTIONS --] FILE [...]"
  exit 1
fi

declare -A fnames
for fname in "$@"; do
  while :; do
    if [[ -z ${fnames["$fname"]+set} ]]; then
      fnames["$fname"]="set"
      printf '%s\0' "${fname:-}"
    fi
    [[ $fname == "/" ]] && break
    fname_tmp="${fname%/*}"
    [[ $fname_tmp == "$fname" ]] && break
    fname="${fname_tmp:-/}"
  done
done \
|xargs -0 "$cmd" ${cmd_opts[@]+"${cmd_opts[@]}"} -- \
;
