#!/bin/bash
##
## List specified files and all parent directories
##
## SPDX-FileCopyrightText: 2013-2025 SATOH Fumiyasu @ OSSTech Corp., Japan
## SPDX-License-Identifier: GPL-3.0-or-later
##

set -u

typeset -a ls_opts
while [[ $# -gt 0 ]]; do
  [[ $1 == "--" ]] && { shift; break; }
  [[ -n "${1##-*}" ]] && break
  ls_opts=(${ls_opts[@]+"${ls_opts[@]}"} "$1")
  shift
done

declare -A fnames
for fname in "$@"; do
  if [[ -n "${fname##/*}" ]]; then
    ## Convert a relative path to an absolute path
    fname="$PWD/$fname"
    ## "/path/to/." -> "/path/to/./"
    fname="${fname/%\/.//./}"
    ## "/path/./to/./dir" -> "/path/to/dir"
    fname="${fname//\/.\///}"
    ## "/path/to/.." -> "/path/to/../"
    fname="${fname/%\/..//../}"
    while :; do
      ## "/path/to/../dir" -> "/path/to"
      fname_left="${fname%%/../*}"
      [[ "$fname_left" == "$fname" ]] && break
      ## "/path/to/../dir" -> "dir"
      fname_right="${fname#*/../}"
      ## -> "/path/dir"
      fname="${fname_left%/*}/$fname_right"
    done
  fi
  ## "/path/to/dir/" -> "/path/to/dir"
  fname="${fname%/}"

  while :; do
    if [[ -z ${fnames["$fname"]-} ]]; then
      fnames["$fname"]="set"
      printf '%s\0' "${fname:-}"
    fi
    [[ $fname == "/" ]] && break
    fname_tmp="${fname%/*}"
    [[ $fname_tmp == "$fname" ]] && break
    fname="${fname_tmp:-/}"
  done
done \
|xargs -0 ls -d ${ls_opts[@]+"${ls_opts[@]}"} -- \
;
