#!/usr/bin/env ruby
##
## Print QR Code by ASCII-Art
## Copyright (c) 2013 SATOH Fumiyasu @ OSS Technology Corp., Japan
##
## License: GNU General Public License version 3
##

## TODO: Print QR Code in sixel image

require "rqrcode"

qrc = RQRCode::QRCode.new(ARGV.size == 0 ? $stdin.readline.chomp : ARGV[0])
t_reset = `tput sgr0`
t_white = `tput setab 7` + '  ' + t_reset
t_black = `tput setab 0` + '  ' + t_reset
puts qrc.
  to_s.
  gsub(/(^|$)/, ' ').
  sub(/\A.*$/) {|m|
    m.gsub(/./, ' ') + "\n" + m
  }.
  sub(/^.*\Z/) {|m|
    m + "\n" + m.gsub(/./, ' ')
  }.
  gsub(' ', t_white).
  gsub('x', t_black)

exit(0)

