#!/usr/bin/env ruby

require "rqrcode"

if ARGV.size != 1
  puts "Usage: #{$PROGRAM_NAME} TEXT"
  exit(1)
end

qrc = RQRCode::QRCode.new(ARGV[0])
black = `tput setab 7` + '  ' + `tput sgr0`
white = `tput setab 0` + '  ' + `tput sgr0`
puts qrc.
  to_s.
  gsub(/(^|$)/, ' ').
  sub(/\A.*$/) {|m|
    m.gsub(/./, ' ') + "\n" + m
  }.
  sub(/^.*\Z/) {|m|
    m + "\n" + m.gsub(/./, ' ')
  }.
  gsub(' ', black).
  gsub('x', white)

exit(0)

