#!/usr/bin/awk -f
##
## Sum up all numbers (ignore others) in stdin
## Copyright (c) 2013 SATOH Fumiyasu @ OSS Technology Corp., Japan
##
## License: GNU General Public License version 3
##

BEGIN {
  sum=0
}

{
  while (NF) {
    sum+=$(NF)
    NF--
  }
}

END {
  print sum
}

