#!/bin/bash
# or
#!/bin/ksh
##
## Do `tail -f FILE` and exit when PATTERN is found
## Copyright (c) 2012-2016 SATOH Fumiyasu @ OSS Technology Corp, Japan
##               <http://www.OSSTech.co.jp/>
##               <https://GitHub.com/fumiyas/>
##
## License: GNU General Public License version 3
##
## Inspired by: http://blog.riywo.com/2012/08/08/042340
##

set -u

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 PATTERN FILE ..."
  exit 1
fi

pattern="${1//\//\\\/}"; shift

tail -f "$@" |(sed "/$pattern/q"; kill -TERM -$$)

