#!/bin/sh
##
## Zebra-ize text lines
## Copyright (C) 2013-2015 SATOH Fumiyasu @ OSS Technology Corp., Japan
##               <https://github.com/fumiyas/home-commands/blob/master/zbr>
##               <https://fumiyas.github.io/>
##
## License: GNU General Public License version 3
##

## TODO: zbr-ize numbers

set -u

t_cr=`tput cr`
t_cols=`tput cols`
#t_deco=`tput smul`
t_deco=`tput setab 8`
t_reset=`tput sgr0`

l_deco=`printf '%s%*s%s%s' "$t_deco" "$t_cols" ' ' "$t_reset" "$t_cr"`

sed \
  -e 'n;n;n' \
  -e "s/\(\[[0-9;]*m\)/\1$t_deco/g" \
  -e "s/^/$l_deco/" \
  -e "s/$t_cr/$t_cr$t_deco/" \
  -e "s/\$/$t_reset/" \
  "$@" \
;

exit 0

