#!/bin/sh
##
## Zebra-ize text lines
## Copyright (C) 2013 SATOH Fumiyasu @ OSS Technology Corp., Japan
##               <https://github.com/fumiyas/home-commands/blob/master/zbr>
##               <https://twitter.com/satoh_fumiyasu>
##
## License: GNU General Public License version 3
##

set -u

t_cols="`tput cols`"
t_bg="`tput setab 8`"
if [ -t 1 ]; then
  t_reset="`tput sgr0`"
else
  t_reset=''
fi

x=0
cat ${1+"$@"} \
|while IFS= read -r line; do
  [ $x -eq 1 ] && echo -n "$t_bg"
  printf "%-${t_cols}s%s\n" "$line" "$t_reset"
  let 'x^=1'
done

exit 0

